import { useMemo } from 'react'

function downloadBlob(filename: string, blob: Blob) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  a.remove()
  URL.revokeObjectURL(url)
}

function toTxtReport(params: Record<string, unknown>) {
  const keys = Object.keys(params).sort((a, b) => a.localeCompare(b))
  const lines: string[] = []
  lines.push('Rigid Pavement Configuration')
  lines.push('Generated by Pavement AI Assistant')
  lines.push('----------------------------------------')
  lines.push('')
  for (const k of keys) {
    lines.push(`${k}: ${String(params[k])}`)
  }
  lines.push('')
  lines.push(`Date: ${new Date().toISOString()}`)
  return lines.join('\n')
}

export default function ParamsPanel(props: {
  progress: { done: number; total: number }
  paramInfo: Record<string, any> | null
  collected: Record<string, unknown> | null
  finalParams: Record<string, unknown> | null
}) {
  const { progress, paramInfo, collected, finalParams } = props

  const keys = useMemo(() => {
    if (paramInfo) return Object.keys(paramInfo)
    if (collected) return Object.keys(collected)
    return []
  }, [paramInfo, collected])

  const rows = useMemo(() => {
    if (!keys.length) return []
    const source = collected || {}
    return keys.map((k) => {
      const meta = paramInfo?.[k]
      // Preferred display name: "name" (Friendly) > "technical_name" > key
      const mainLabel = meta?.name || meta?.technical_name || k

      return {
        key: k,
        value: source[k],
        mainLabel,
      }
    })
  }, [keys, collected, paramInfo])

  const percent = progress.total > 0 ? Math.round((progress.done / progress.total) * 100) : 0

  return (
    <div className="params-panel">
      <div className="panel-header">
        <h3>Configuration Status</h3>
        <span style={{ fontSize: '12px', color: 'var(--text-secondary)' }}>
           {progress.done} / {progress.total} Completed
        </span>
      </div>

      <div style={{ marginBottom: '24px' }}>
        <div style={{ height: '4px', background: 'var(--bg-subtle)', borderRadius: '2px', overflow: 'hidden' }}>
          <div style={{ width: `${percent}%`, height: '100%', background: 'var(--accent)', transition: 'width 0.3s ease' }} />
        </div>
      </div>

      <div className="card">
        <div className="card-header">
           <h3>Collected Parameters</h3>
        </div>
        <div className="card-body" style={{ padding: 0 }}>
          {rows.length ? (
            <div className="table-wrap" style={{ border: 'none', borderRadius: 0 }}>
              <table className="table">
                <thead>
                  <tr>
                    <th style={{ width: '50%' }}>Parameter</th>
                    <th>Value</th>
                  </tr>
                </thead>
                <tbody>
                  {rows.map((r) => (
                    <tr key={r.key}>
                      <td>
                        <div style={{ fontWeight: 500, fontSize: '13px' }}>{r.mainLabel}</div>
                      </td>
                      <td>
                        {r.value === undefined || r.value === null || String(r.value) === '' ? 
                          <span className="sub" style={{ opacity: 0.5 }}>—</span> : 
                          <span style={{ fontWeight: 500 }}>{String(r.value)}</span>
                        }
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <div style={{ padding: '16px', textAlign: 'center' }} className="sub">
              Parameters will appear here.
            </div>
          )}
        </div>
      </div>

      {finalParams && (
        <div style={{ marginTop: '24px' }}>
             <button 
                className="btn primary" 
                style={{ width: '100%' }}
                onClick={() => {
                   const txt = toTxtReport(finalParams)
                   const blob = new Blob([txt], { type: 'text/plain' })
                   downloadBlob('pavement-config.txt', blob)
                }}
             >
                Export Configuration
             </button>
        </div>
      )}
    </div>
  )
}
