import { useMemo, useState } from 'react'
import { getParamDisplayLabel } from '../lib/displayLabels'
import { validateInlineEngineeringEdit } from '../lib/engineeringValidation'

const HIDDEN_COLLECTED_KEYS = new Set<string>([])

const EDITABLE_KEYS = new Set([
  'Emod',
  'nu',
  'a',
  'b',
  't',
  'Kx',
  'Ky',
  'Kz',
  'x1',
  'x2',
  'y1',
  'y2',
  'mesh_type',
  'load_location',
])

function downloadBlob(filename: string, blob: Blob) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  a.remove()
  URL.revokeObjectURL(url)
}

function toTxtReport(params: Record<string, unknown>) {
  const keys = Object.keys(params).sort((a, b) => a.localeCompare(b))
  const lines: string[] = []
  lines.push('Rigid Pavement Configuration')
  lines.push('Generated by Pavement AI Assistant')
  lines.push('----------------------------------------')
  lines.push('')
  for (const k of keys) {
    const value = params[k]
    lines.push(`${k}: ${typeof value === 'object' && value !== null ? JSON.stringify(value) : String(value)}`)
  }
  lines.push('')
  lines.push(`Date: ${new Date().toISOString()}`)
  return lines.join('\n')
}

function sanitizeExportPayload(payload: Record<string, unknown>): Record<string, unknown> {
  const cloned = JSON.parse(JSON.stringify(payload)) as Record<string, unknown>
  delete cloned.mesh_type
  delete cloned.load_location
  return cloned
}

export default function ParamsPanel(props: {
  progress: { done: number; total: number }
  paramInfo: Record<string, any> | null
  collected: Record<string, unknown> | null
  finalParams: Record<string, unknown> | null
  busy: boolean
  // When true, export buttons are enabled.
  finalConfirmed: boolean
  onConfirmFinal: () => void
  analysisBusy: boolean
  analysisError: string | null
  analysisResult: {
    success: boolean
    message: string
    input_json_path?: string | null
    output_dir?: string | null
    vtk_file?: string | null
    results_file?: string | null
    summary_file?: string | null
    detailed_report?: Record<string, unknown> | null
    solver_stdout?: string | null
  } | null
  onGenerateAnalysis: () => Promise<void> | void
  // Edits are applied by the parent (e.g., via backend chat/state update).
  onEditParam: (key: string, value: string) => Promise<void> | void
}) {
  const {
    progress,
    paramInfo,
    collected,
    finalParams,
    busy,
    finalConfirmed,
    onConfirmFinal,
    analysisBusy,
    analysisError,
    analysisResult,
    onGenerateAnalysis,
    onEditParam,
  } = props

  // Inline edit state (Collected Parameters panel).
  const [rowEditingKey, setRowEditingKey] = useState<string | null>(null)
  const [rowDraftValue, setRowDraftValue] = useState('')
  const [rowEditError, setRowEditError] = useState<string | null>(null)
  const [rowEditWarning, setRowEditWarning] = useState<string | null>(null)
  const [rowSaving, setRowSaving] = useState(false)
  const [rowNotice, setRowNotice] = useState<{ key: string; message: string } | null>(null)

  const keys = useMemo(() => {
    if (paramInfo) {
      return Object.keys(paramInfo).filter((k) => !HIDDEN_COLLECTED_KEYS.has(k))
    }
    if (collected) {
      return Object.keys(collected).filter((k) => !HIDDEN_COLLECTED_KEYS.has(k))
    }
    return []
  }, [paramInfo, collected])

  function renderValueForEdit(v: unknown): string {
    if (v === undefined || v === null) return ''
    if (typeof v === 'string') return v
    if (typeof v === 'number') return String(v)
    try {
      return JSON.stringify(v)
    } catch {
      return String(v)
    }
  }

  function canEditKey(key: string): boolean {
    if (key === 'x' || key === 'y' || key === 'q') return false
    return EDITABLE_KEYS.has(key)
  }

  function asNumberArray(v: unknown): number[] | null {
    if (!Array.isArray(v)) return null
    const nums = v.map((n) => (typeof n === 'number' ? n : Number(n)))
    if (nums.some((n) => !Number.isFinite(n))) return null
    return nums
  }

  function formatNodeArrayPreview(arr: number[], maxItems = 4) {
    const full = `[${arr.join(',')}]`
    const preview =
      arr.length > maxItems
        ? `[${arr.slice(0, maxItems).join(',')},...]`
        : `[${arr.join(',')}]`
    return { preview, full }
  }

  function validateRowEdit(key: string, raw: string): { error: string | null; warning: string | null; normalizedValue: string } {
    const trimmedKey = key.trim()
    if (!canEditKey(trimmedKey)) {
      return { error: 'This parameter cannot be edited.', warning: null, normalizedValue: raw.trim() }
    }

    const res = validateInlineEngineeringEdit({
      key: trimmedKey,
      rawValue: raw,
      currentParams: collected ?? {},
    })

    if (!res.ok) {
      return { error: res.error, warning: null, normalizedValue: res.normalizedValue }
    }

    return { error: null, warning: res.warning ?? null, normalizedValue: res.normalizedValue }
  }

  const rows = useMemo(() => {
    if (!keys.length) return []
    const source = collected || {}
    return keys.map((k) => {
      const meta = paramInfo?.[k]
      const mainLabel = getParamDisplayLabel(k, meta)

      return {
        key: k,
        symbol: k,
        value: source[k],
        mainLabel,
      }
    })
  }, [keys, collected, paramInfo])

  const percent = progress.total > 0 ? Math.round((progress.done / progress.total) * 100) : 0

  return (
    <div className="params-panel">
      <div className="panel-header">
        <h3>Configuration Status</h3>
        <span style={{ fontSize: '12px', color: 'var(--text-secondary)' }}>
           {progress.done} / {progress.total} Completed
        </span>
      </div>

      <div style={{ marginBottom: '24px' }}>
        <div style={{ height: '4px', background: 'var(--bg-subtle)', borderRadius: '2px', overflow: 'hidden' }}>
          <div style={{ width: `${percent}%`, height: '100%', background: 'var(--accent)', transition: 'width 0.3s ease' }} />
        </div>
      </div>

      <div className="card">
        <div className="card-header">
           <h3>Collected Parameters</h3>
        </div>
        <div className="card-body" style={{ padding: 0 }}>
          {rows.length ? (
            <div className="table-wrap" style={{ border: 'none', borderRadius: 0 }}>
              <table className="table params-collected-table">
                <colgroup>
                  <col style={{ width: '40%' }} />
                  <col style={{ width: '60%' }} />
                  <col style={{ width: '72px' }} />
                </colgroup>
                <thead>
                  <tr>
                    <th>Parameter</th>
                    <th>Value</th>
                    <th aria-label="Edit" />
                  </tr>
                </thead>
                <tbody>
                  {rows.map((r) => (
                    <tr key={r.key}>
                      <td>
                        <div className="param-label-wrap">
                          <span className="param-symbol" title={`Symbol: ${r.symbol}`}>{r.symbol}</span>
                          <span className="param-main-label">{r.mainLabel}</span>
                        </div>
                      </td>
                      <td className="param-value-cell">
                        {rowEditingKey === r.key && canEditKey(r.key) ? (
                          <>
                            {r.key === 'mesh_type' ? (
                              <select
                                className="param-edit-input"
                                value={(() => {
                                  const v = rowDraftValue.trim().toLowerCase()
                                  return ['coarse', 'medium', 'fine'].includes(v) ? v : 'medium'
                                })()}
                                onChange={(e) => {
                                  setRowEditError(null)
                                  setRowEditWarning(null)
                                  setRowDraftValue(e.target.value)
                                }}
                                disabled={busy || rowSaving}
                              >
                                <option value="coarse">coarse</option>
                                <option value="medium">medium</option>
                                <option value="fine">fine</option>
                              </select>
                            ) : r.key === 'load_location' ? (
                              <select
                                className="param-edit-input"
                                value={(() => {
                                  const v = rowDraftValue.trim().toLowerCase()
                                  return ['corner', 'edge', 'interior'].includes(v) ? v : 'interior'
                                })()}
                                onChange={(e) => {
                                  setRowEditError(null)
                                  setRowEditWarning(null)
                                  setRowDraftValue(e.target.value)
                                }}
                                disabled={busy || rowSaving}
                              >
                                <option value="corner">corner</option>
                                <option value="edge">edge</option>
                                <option value="interior">interior</option>
                              </select>
                            ) : (
                              <input
                                className="param-edit-input"
                                type="number"
                                inputMode="decimal"
                                step="any"
                                value={rowDraftValue}
                                onChange={(e) => {
                                  setRowEditError(null)
                                  setRowEditWarning(null)
                                  setRowDraftValue(e.target.value)
                                }}
                                placeholder="Enter value"
                                disabled={busy || rowSaving}
                                autoComplete="off"
                              />
                            )}

                            {rowEditWarning && (
                              <div className="sub" style={{ marginTop: '6px', color: 'var(--warning)' }}>
                                {rowEditWarning}
                              </div>
                            )}
                          </>
                        ) : (
                          <>
                            {r.value === undefined || r.value === null || String(r.value) === '' ? (
                              <span className="sub" style={{ opacity: 0.5 }}>—</span>
                            ) : r.key === 'x' || r.key === 'y' ? (
                              (() => {
                                const nums = asNumberArray(r.value)
                                if (!nums) {
                                  return <span className="param-value-display">{typeof r.value === 'object' ? JSON.stringify(r.value) : String(r.value)}</span>
                                }
                                const { preview, full } = formatNodeArrayPreview(nums)
                                return (
                                  <span className="param-array-preview" title={full} aria-label={full}>
                                    {preview}
                                  </span>
                                )
                              })()
                            ) : (
                              <span className="param-value-display">{typeof r.value === 'object' ? JSON.stringify(r.value) : String(r.value)}</span>
                            )}

                            {rowNotice?.key === r.key && (
                              <div className="sub" style={{ marginTop: '6px', color: 'var(--warning)' }}>
                                {rowNotice.message}
                              </div>
                            )}
                          </>
                        )}

                        {rowEditingKey === r.key && canEditKey(r.key) && rowEditError && (
                          <div className="sub" style={{ marginTop: '6px', color: 'var(--danger)' }}>
                            {rowEditError}
                          </div>
                        )}
                      </td>

                      <td className="param-actions-cell">
                        {rowEditingKey === r.key && canEditKey(r.key) ? (
                          <div className="param-actions">
                            <button
                              type="button"
                              className="param-edit-btn"
                              title="Cancel"
                              aria-label="Cancel"
                              disabled={busy || rowSaving}
                              onClick={() => {
                                setRowEditError(null)
                                setRowEditWarning(null)
                                setRowEditingKey(null)
                                setRowDraftValue('')
                              }}
                            >
                              ✕
                            </button>

                            <button
                              type="button"
                              className="param-edit-btn"
                              title="Save"
                              aria-label="Save"
                              disabled={busy || rowSaving}
                              onClick={async () => {
                                const { error, warning, normalizedValue } = validateRowEdit(r.key, rowDraftValue)
                                if (error) {
                                  setRowEditError(error)
                                  return
                                }

                                setRowSaving(true)
                                setRowEditError(null)
                                setRowEditWarning(warning)
                                try {
                                  const outgoing = normalizedValue
                                  await Promise.resolve(onEditParam(r.key, outgoing))

                                  if (warning) {
                                    setRowNotice({ key: r.key, message: warning })
                                    window.setTimeout(() => {
                                      setRowNotice((prev) => (prev?.key === r.key ? null : prev))
                                    }, 8000)
                                  } else {
                                    setRowNotice((prev) => (prev?.key === r.key ? null : prev))
                                  }

                                  setRowEditingKey(null)
                                  setRowDraftValue('')
                                  setRowEditWarning(null)
                                } catch (e) {
                                  setRowEditError((e as Error).message)
                                } finally {
                                  setRowSaving(false)
                                }
                              }}
                            >
                              ✓
                            </button>
                          </div>
                        ) : canEditKey(r.key) ? (
                          <div className="param-actions">
                            <button
                              type="button"
                              className="param-edit-btn"
                              title={`Edit ${r.key}`}
                              aria-label={`Edit ${r.key}`}
                              disabled={busy || rowSaving}
                              onClick={() => {
                                setRowEditError(null)
                                setRowEditWarning(null)
                                setRowNotice((prev) => (prev?.key === r.key ? null : prev))
                                setRowEditingKey(r.key)
                                const start = renderValueForEdit(r.value)
                                setRowDraftValue(start)
                              }}
                            >
                              ✎
                            </button>
                          </div>
                        ) : null}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <div style={{ padding: '16px', textAlign: 'center' }} className="sub">
              Parameters will appear here.
            </div>
          )}
        </div>
      </div>

      {finalParams && (
        <div style={{ marginTop: '24px' }}>
          <div className="card">
            <div className="card-header">
              <h3>Export</h3>
            </div>
            <div className="card-body">
              {!finalConfirmed ? (
                <>
                  <div className="sub" style={{ marginBottom: '12px' }}>
                    Export is disabled until you confirm.
                  </div>
                  <button
                    className="btn primary"
                    style={{ width: '100%' }}
                    disabled={busy}
                    onClick={onConfirmFinal}
                  >
                    Enable export
                  </button>
                </>
              ) : (
                <>
                  <button
                    className="btn primary"
                    style={{ width: '100%' }}
                    onClick={() => {
                      void onGenerateAnalysis()
                    }}
                    disabled={busy || analysisBusy}
                  >
                    {analysisBusy ? 'Generating Analysis...' : 'Generate Analysis'}
                  </button>

                  {analysisError && (
                    <div className="status-detail warning" style={{ marginTop: '12px' }}>
                      {analysisError}
                    </div>
                  )}

                  {analysisResult && (
                    <div
                      className="status-detail"
                      style={{
                        marginTop: '12px',
                        borderColor: analysisResult.success ? 'var(--success)' : 'var(--danger)',
                      }}
                    >
                      <strong>{analysisResult.success ? 'Analysis completed.' : 'Analysis failed.'}</strong>
                      <div>{analysisResult.message}</div>
                      {analysisResult.vtk_file && <div>VTK: {analysisResult.vtk_file}</div>}
                      {analysisResult.summary_file && <div>Summary: {analysisResult.summary_file}</div>}
                      {analysisResult.results_file && <div>Results: {analysisResult.results_file}</div>}
                    </div>
                  )}

                  <button
                    className="btn primary"
                    style={{ width: '100%', marginTop: '10px' }}
                    onClick={() => {
                      const sanitized = sanitizeExportPayload(finalParams)
                      const prettyJson = JSON.stringify(sanitized, null, 2)
                      const blob = new Blob([prettyJson], { type: 'application/json' })
                      downloadBlob('pavement-config.json', blob)
                    }}
                  >
                    Export Final JSON
                  </button>

                  <button
                    className="btn"
                    style={{ width: '100%', marginTop: '10px' }}
                    onClick={() => {
                      const txt = toTxtReport(sanitizeExportPayload(finalParams))
                      const blob = new Blob([txt], { type: 'text/plain' })
                      downloadBlob('pavement-config.txt', blob)
                    }}
                  >
                    Export Text Report
                  </button>
                </>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
